Spike/sc 1517
epcpower/m-pm pull request #4
Opened 2024-05-02 17:15 UTC by abnepc

## Jira Story
[SC-1517](https://epcpower.atlassian.net/browse/SC-1517)
## About
Investigate/remove `sunspecdemo` from the repo
## Associated Pull Requests
* [stlib]()
* [st]()
* [pm]()
* [grid-tied]()
* [rm-dc]()
* [m-pm]()
* [m-bcu]()
* [m-tcu]()
## Reproduction Steps
N/A
## Validation
Delete your `.venv` folder and do a `poetry install`. Then make sure that `sunspecdemo` was not installed. 

[SC-1517]: https://epcpower.atlassian.net/browse/SC-1517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-02 21:04 UTC, epcAnker commented on .vscode/settings.json
> +  "conventionalCommits.scopes": ["SC-1517"]
remove file, gitignore

2024-05-02 21:08 UTC, epcAnker requested changes
Remove MPM_ folder from PR

"epcpm" changes needed in:
README.rst
.gitattributes
src/mpm/__main__.py "    file_handler = logging.FileHandler("epcpm.log")"

Look into:
epcpmcli_Linux_xml (and other xml files)
*.py files with "epcpm" they are all commented


Would also recommend looking at *.py files

2024-05-03 18:28 UTC, epcAnker requested changes

2024-05-03 18:28 UTC, epcAnker commented on pyproject.toml
> +version = "0.0.0.post1176.dev0+6680080"
revert back to 0.0.0

2024-05-03 18:28 UTC, epcAnker commented on src/mpm/__build.py
> +# This file has been generated
remove generated file

2024-05-03 18:28 UTC, epcAnker commented on src/mpm/__init__.py
> +__version__ = "0.0.0.post1176.dev0+6680080"
set back to 0.0.0

2024-05-03 18:28 UTC, epcAnker commented on src/mpm/__version.py
> +# This file was automatically generated by sub/epyqlib/epyqlib/cli/generateversion.py
remove generated file

2024-05-03 18:28 UTC, epcAnker commented on pyproject.toml
> +builduipm = 'mpm.builduipm:compile_ui'
@gordon-epc do we want to change builduipm-builduimpm?

2024-05-03 18:28 UTC, epcAnker commented on src/mpm/builduipm.py
@gordon-epc do we want to change builduipm->buildui**mpm**?

2024-05-03 18:28 UTC, epcAnker commented on src/mpm/cantoxlsx.py
> +import mpm.pm_helper
@gordon-epc do we want pm\_helper -> mpm\_helper???

2024-05-03 18:28 UTC, epcAnker commented on src/mpm/tests/test_canmodel_parametermodel.json
can likely delete this file?

2024-05-06 22:58 UTC, gordon-epc requested changes

2024-05-06 22:58 UTC, gordon-epc commented on MPM__/Pint-0.11.dist-info/AUTHORS
This whole `MPM__` directory should not be checked in. Where did it come from?

2024-05-06 22:59 UTC, gordon-epc commented on src/mpm/builduipm.py
All or nothing.

2024-05-06 22:59 UTC, gordon-epc commented on src/mpm/cantoxlsx.py
> +import mpm.pm_helper
All or nothing.

2024-05-16 21:23 UTC, abnepc commented on MPM__/Pint-0.11.dist-info/AUTHORS
[f49d990](https://github.com/epcpower/m-pm/pull/4/commits/f49d990f1b0aa7aa9379d79f1c85656c231abbae)

2024-05-16 21:24 UTC, abnepc commented on .vscode/settings.json
> +  "conventionalCommits.scopes": ["SC-1517"]
[ad51c84](https://github.com/epcpower/m-pm/pull/4/commits/ad51c84889958c333709fa33d6fefebf35dcd131) and [3ab51e1](https://github.com/epcpower/m-pm/pull/4/commits/3ab51e1be9e2efb3054dce62ab423dc1d0a8719c)

2024-05-16 21:46 UTC, abnepc commented on src/mpm/__version.py
> +# This file was automatically generated by sub/epyqlib/epyqlib/cli/generateversion.py
[49542d1](https://github.com/epcpower/m-pm/pull/4/commits/49542d19bbe919340d7f070f1a2ea1312f23ed93)

2024-05-16 21:46 UTC, abnepc commented on src/mpm/__build.py
> +# This file has been generated
[49542d1](https://github.com/epcpower/m-pm/pull/4/commits/49542d19bbe919340d7f070f1a2ea1312f23ed93)

2024-05-16 21:46 UTC, abnepc commented on src/mpm/__init__.py
> +__version__ = "0.0.0.post1176.dev0+6680080"
[52420a3](https://github.com/epcpower/m-pm/pull/4/commits/52420a389ef01663be40abb3e52637d4c26c4b7b)

2024-05-16 21:46 UTC, abnepc commented on pyproject.toml
> +version = "0.0.0.post1176.dev0+6680080"
[52420a3](https://github.com/epcpower/m-pm/pull/4/commits/52420a389ef01663be40abb3e52637d4c26c4b7b)

2024-05-16 21:53 UTC, abnepc commented on src/mpm/cantoxlsx.py
> +import mpm.pm_helper
[ac96c9f](https://github.com/epcpower/m-pm/pull/4/commits/ac96c9f72ad23da10b920515bcea1aa3bf8b6d84)

2024-05-16 21:53 UTC, abnepc commented on src/mpm/builduipm.py
[ac96c9f](https://github.com/epcpower/m-pm/pull/4/commits/ac96c9f72ad23da10b920515bcea1aa3bf8b6d84)

2024-05-16 21:53 UTC, abnepc commented on src/mpm/tests/test_canmodel_parametermodel.json
[cb38c74](https://github.com/epcpower/m-pm/pull/4/commits/cb38c744cd8c9d42256c751e57fc371f2ee9c4fc)

2024-05-16 21:54 UTC, abnepc commented on pyproject.toml
> +builduipm = 'mpm.builduipm:compile_ui'
[ac96c9f](https://github.com/epcpower/m-pm/pull/4/commits/ac96c9f72ad23da10b920515bcea1aa3bf8b6d84)

2024-05-23 19:46 UTC, abnepc commented
> Remove MPM_ folder from PR
> 
> "epcpm" changes needed in: README.rst .gitattributes src/mpm/**main**.py " file_handler = logging.FileHandler("epcpm.log")"
> 
> Look into: epcpmcli_Linux_xml (and other xml files) *.py files with "epcpm" they are all commented
> 
> Would also recommend looking at *.py files

[ce80509](https://github.com/epcpower/m-pm/pull/4/commits/ce80509fb97d396436cfcd70432cf612227db589) and [fc124d5](https://github.com/epcpower/m-pm/pull/4/commits/fc124d55b963944fdbd36f31076c6e3b6b6eddd7). As for files in `.idea` directory, those should've been an a `.gitignore`. I have an adjacent PR that adds to the `.gitignore` and can add it there if you'd prefer?

2024-05-31 08:48 UTC, vvainola approved these changes

2024-05-31 22:38 UTC, gordon-epc approved these changes

2024-06-03 18:45 UTC, epcAnker approved these changes

2024-06-04 20:10 UTC, merged